line-length = 120
indent-width = 4

exclude = [
    ".venv",
]

[lint]
select = [
    # pycodestyle
    "E",
    "W",
    # pep8-naming
    "N",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C",
    # flake8-simplify
    "SIM",
    # isort - check imports
    "I",
    # flake8-pyi
    "PYI",
    # flake8-quotes
    "Q",
    # flake8-self
    "SLF",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # Pylint Warning
    "PLW",
    # Pylint Error
    "PLE"
]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[lint.flake8-quotes]
inline-quotes = "single"